### ISSUE TITLE
Can't build on macOS (I'm noob)

### ISSUE THREAD

**Issue by Dolfost** [DingShizhe/Desmos-Desktop#4]
I am building Desmos Desktop from source on MacOS Ventura 13.0.1 
When I building it I get some errors and can't figure out how to solve them (I'm not an professional in Linux and totally new to Mac)

There is the last x lines of output:
```
npm timing metavuln:calculate:security-advisory:electron-builder:/m9e3+4eZoJfOIwv8u2YcZKESjn0cIhdUiW+L61QXSBmG2KZi6k99KfoVT97S8J5FhMGkfsm3PSLHKAk2BZ2jw== Completed in 2ms
npm timing metavuln:packument:update-notifier Completed in 0ms
npm timing metavuln:cache:get:security-advisory:update-notifier:xP9mRUu7m2mo/448iOKQBNLQe2N0zzOtFmffIfl+EP72ua2qlDbi4Wmy47kf6ngmCp6oXq5KSrlC0sT177Bjvg== Completed in 0ms
npm timing metavuln:load:security-advisory:update-notifier:px3BGTh0zXO0FGPeGweQ9jqShrQQXkwvso85ThJdSYlN4ZaZJDL3uEj6l9X6a7TaVNgKnd3jqWD9VSx0Ti/yzQ== Completed in 0ms
npm timing metavuln:calculate:security-advisory:update-notifier:px3BGTh0zXO0FGPeGweQ9jqShrQQXkwvso85ThJdSYlN4ZaZJDL3uEj6l9X6a7TaVNgKnd3jqWD9VSx0Ti/yzQ== Completed in 0ms
npm timing metavuln:cache:get:security-advisory:electron-builder:YsUyPVjiTjxWw/RfhFcyPCsH2D4Q7F2whBXLLS22kSNogjq+UMk+WUbPIOy7yhM8SUKHtlPS2rvSWeFC947B9Q== Completed in 1ms
npm timing metavuln:load:security-advisory:electron-builder:xP9mRUu7m2mo/448iOKQBNLQe2N0zzOtFmffIfl+EP72ua2qlDbi4Wmy47kf6ngmCp6oXq5KSrlC0sT177Bjvg== Completed in 1ms
npm timing metavuln:calculate:security-advisory:electron-builder:xP9mRUu7m2mo/448iOKQBNLQe2N0zzOtFmffIfl+EP72ua2qlDbi4Wmy47kf6ngmCp6oXq5KSrlC0sT177Bjvg== Completed in 2ms
npm timing auditReport:init Completed in 59ms
npm timing reify:audit Completed in 1055ms
npm info run electron@3.1.13 postinstall { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 119ms
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 1711ms
npm ERR! code 1
npm ERR! path /Users/vladyslav/Desmos-Desktop/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c -- node install.js
Downloading tmp-14475-0-electron-v3.1.13-darwin-arm64.zip
npm ERR! Error: GET https://github.com/electron/electron/releases/download/v3.1.13/electron-v3.1.13-darwin-arm64.zip returned 404
npm ERR! /Users/vladyslav/Desmos-Desktop/node_modules/electron/install.js:49
npm ERR!   throw err
npm ERR!   ^
npm ERR!
npm ERR! Error: Failed to find Electron v3.1.13 for darwin-arm64 at https://github.com/electron/electron/releases/download/v3.1.13/electron-v3.1.13-darwin-arm64.zip
npm ERR!     at Request.<anonymous> (/Users/vladyslav/Desmos-Desktop/node_modules/nugget/index.js:197:61)
npm ERR!     at Request.emit (node:events:513:28)
npm ERR!     at Request.onRequestResponse (/Users/vladyslav/Desmos-Desktop/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:688:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:530:22)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR!
npm ERR! Node.js v19.2.0
npm timing npm Completed in 1753ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladyslav/.npm/_logs/2022-12-07T19_15_38_193Z-debug-0.log
sh: electron-builder: command not found
cd: no such file or directory: dist
➜  Desmos-Desktop git:(master)
```

How to install Desmos Desktop?

**Comment by SpiritAxolotl** [comment]
Hey! Old reply but I figured this out just now since I had the same problem. Running `npm install electron@latest` before `npm install -d` (inside the Desmos-Desktop directory) made it build properly. The error has to do with that electron version not having a build for macOS arm64, so upgrading fixes it.

**Comment by Dolfost** [comment]
> Hey! Old reply but I figured this out just now since I had the same problem. Running `npm install electron@latest` before `npm install -d` (inside the Desmos-Desktop directory) made it build properly. The error has to do with that electron version not having a build for macOS arm64, so upgrading fixes it.

I tried to do so, but got the:

```
➜  Desmos-Desktop git:(master) npm install electron@latest
npm WARN deprecated electron-osx-sign@0.4.11: Please use @electron/osx-sign moving forward. Be aware the API is slightly different

added 276 packages, and audited 277 packages in 24s

30 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (4 moderate, 2 high, 2 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
➜  Desmos-Desktop git:(master) ✗ npm install -d
npm run dist
cd dist && ls
npm info using npm@10.5.0
npm info using node@v21.7.3
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 324ms
npm http fetch GET 200 https://registry.npmjs.org/ejs 54ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/got 189ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/app-builder-lib 196ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/electron-builder 140ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/dmg-builder 154ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/package-json 55ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/latest-version 888ms (cache updated)
npm http fetch GET 200 https://registry.npmjs.org/update-notifier 58ms (cache updated)

up to date, audited 277 packages in 2s

30 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (4 moderate, 2 high, 2 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm info ok

> desmos@1.0.0 dist
> electron-builder

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=30.0.1 appOutDir=dist/mac
  • downloading     parts=8 size=102 MB url=https://github.com/electron/electron/releases/download/v30.0.1/electron-v30.0.1-darwin-x64.zip
  • downloaded      duration=21.145s url=https://github.com/electron/electron/releases/download/v30.0.1/electron-v30.0.1-darwin-x64.zip
  • default Electron icon is used reason=application icon is not set
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                               1) 12C13E5B1B894047EF47F9C8C8E043D43C907983 "localhost" (CSSMERR_TP_NOT_TRUSTED)
                                                  1 identities found

                                               Valid identities only
                                                  0 valid identities found
  • building        target=macOS zip arch=x64 file=dist/desmos-1.0.0-mac.zip
  • building        target=DMG arch=x64 file=dist/desmos-1.0.0.dmg
  • building embedded block map file=dist/desmos-1.0.0-mac.zip
Error: Exit code: 2. Command failed: /usr/bin/perl /private/var/folders/fx/lxhzhmnx1l3cd0ymf8xkkgmr0000gn/T/t-3pgysP/1-dmgProperties.pl
Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module) (@INC contains: /Library/Perl/5.34/darwin-thread-multi-2level /Library/Perl/5.34 /Network/Library/Perl/5.34/darwin-thread-multi-2level /Network/Library/Perl/5.34 /Library/Perl/Updates/5.34.1 /System/Library/Perl/5.34/darwin-thread-multi-2level /System/Library/Perl/5.34 /System/Library/Perl/Extras/5.34/darwin-thread-multi-2level /System/Library/Perl/Extras/5.34) at /private/var/folders/fx/lxhzhmnx1l3cd0ymf8xkkgmr0000gn/T/t-3pgysP/1-dmgProperties.pl line 3.
BEGIN failed--compilation aborted at /private/var/folders/fx/lxhzhmnx1l3cd0ymf8xkkgmr0000gn/T/t-3pgysP/1-dmgProperties.pl line 3.

Can't locate Mac/Finder/DSStore.pm in @INC (you may need to install the Mac::Finder::DSStore module) (@INC contains: /Library/Perl/5.34/darwin-thread-multi-2level /Library/Perl/5.34 /Network/Library/Perl/5.34/darwin-thread-multi-2level /Network/Library/Perl/5.34 /Library/Perl/Updates/5.34.1 /System/Library/Perl/5.34/darwin-thread-multi-2level /System/Library/Perl/5.34 /System/Library/Perl/Extras/5.34/darwin-thread-multi-2level /System/Library/Perl/Extras/5.34) at /private/var/folders/fx/lxhzhmnx1l3cd0ymf8xkkgmr0000gn/T/t-3pgysP/1-dmgProperties.pl line 3.
BEGIN failed--compilation aborted at /private/var/folders/fx/lxhzhmnx1l3cd0ymf8xkkgmr0000gn/T/t-3pgysP/1-dmgProperties.pl line 3.

    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/builder-util/src/util.ts:126:16
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:337:12)
From previous event:
    at _applyProperties (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/out/dmgUtil.js:179:27)
    at applyProperties (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/out/dmgUtil.js:166:27)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/src/dmg.ts:307:9
From previous event:
    at _customizeDmg (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/out/dmg.js:458:24)
    at customizeDmg (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/out/dmg.js:402:24)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/src/dmg.ts:48:54
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/src/dmgUtil.ts:37:31
From previous event:
    at _attachAndExecute (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/out/dmgUtil.js:120:28)
    at attachAndExecute (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/out/dmgUtil.js:97:28)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/src/dmg.ts:48:16
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/dmg-builder/src/dmg.ts:21:42)
    at Function.buildAsyncTargets (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at MacPackager.packageInDistributableFormat (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/macPackager.ts:91:26
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/macPackager.ts:91:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/macPackager.ts:82:95)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
    at callback (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:204:5)
From previous event:
    at Packager.doBuild (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:193:23)
From previous event:
    at Packager._build (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (node:internal/timers:478:21)
From previous event:
    at Packager.build (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/vladyslav/tmp/Desmos-Desktop/node_modules/electron-builder/src/builder.ts:228:10)
    at /Users/vladyslav/tmp/Desmos-Desktop/node_modules/electron-builder/src/cli/cli.ts:49:19
builder-debug.yml  builder-effective-config.yaml  desmos-1.0.0-mac.zip  mac
➜  dist git:(master) ✗
```

**Comment by SpiritAxolotl** [comment]
Hm, seems the error you're getting is `Can't locate Mac/Finder/DSStore.pm in @INC`. Try running `npm audit fix --force`, because that's the intermediate step I forgot to mention I did as well (and then try building it).

**Comment by Dolfost** [comment]
> Hm, seems the error you're getting is `Can't locate Mac/Finder/DSStore.pm in @INC`. Try running `npm audit fix --force`, because that's the intermediate step I forgot to mention I did as well (and then try building it).

Thank You! I build desmos successfully!
